# use docker image with latex preinstalled
# since there is no official latex image, use https://github.com/blang/latex-docker
# possible alternative: https://github.com/natlownes/docker-latex, consider making it only for this branch ENGR 446
# Use dirhtml to generate html file needed
#    - mainReport
stages:
    - auxReports
    - publish

    
projectBackground:
  image: blang/latex:ctanfull
  stage: auxReports
  script:
    - cd /builds/studentdavidli/ENGRCoopReportTemplate/Auxillary-Reports/project-background-I
    - pdflatex "engr446milestone1".tex 
    - bibtex "engr446milestone1"
    - pdflatex "engr446milestone1".tex
  artifacts:
    paths:
      - "/builds/studentdavidli/ENGRCoopReportTemplate/Auxillary-Reports/project-background-I/*.pdf"

engineering-analysis-II:
  image: blang/latex:ctanfull
  stage: auxReports
  script:
    - cd /builds/studentdavidli/ENGRCoopReportTemplate/Auxillary-Reports/engineering-analysis-II
    - pdflatex "engr446milestone2".tex 
    - bibtex "engr446milestone2"
    - pdflatex "engr446milestone2".tex
  artifacts:
    paths:
      - "/builds/studentdavidli/ENGRCoopReportTemplate/Auxillary-Reports/engineering-analysis-II/*.pdf"
      
pages:
  stage: publish
  dependencies:
    - engineering-analysis-II
    - projectBackground
  script:
    - mv /builds/studentdavidli/ENGRCoopReportTemplate/Auxillary-Reports/engineering-analysis-II/*.pdf public/
    - mv /builds/studentdavidli/ENGRCoopReportTemplate/Auxillary-Reports/project-background-I/*.pdf public/
    - mv /builds/studentdavidli/ENGRCoopReportTemplate/Auxillary-Reports/index.html public/
  artifacts:
    paths:
      - public
    expire_in: 30 days