# use docker image with latex preinstalled
# since there is no official latex image, use https://github.com/blang/latex-docker
# possible alternative: https://github.com/natlownes/docker-latex
image: blang/latex:ctanfull

build:
  script:
    - cd /builds/studentdavidli/ENGRCoopReportTemplate/Auxillary-Reports/project-background-I
    - pdflatex "engr446milestone1".tex 
    - bibtex "engr446milestone1"
    - pdflatex "engr446milestone1".tex
  artifacts:
    paths:
      - "*.pdf"