# use docker image with latex preinstalled
# since there is no official latex image, use https://github.com/blang/latex-docker
# possible alternative: https://github.com/natlownes/docker-latex
image: blang/latex:ctanfull

build:
  script:
    - lwarpmk cleanall
    - lwarpmk print
    - lwarpmk html
    - lwarpmk pdftohmtl
  artifacts:
    paths:
      - "*.pdf"
      - "*.html"
    allow_failure: true