# use docker image with latex preinstalled
# since there is no official latex image, use https://github.com/blang/latex-docker
# possible alternative: https://github.com/natlownes/docker-latex
image: blang/latex:ctanfull
#    - mainReport
stages:
    - auxReports
    - publish

    
projectBackground:
  stage: auxReports
  script:
    - cd /builds/studentdavidli/ENGRCoopReportTemplate/Auxillary-Reports/project-background-I
    - pdflatex "engr446milestone1".tex 
    - bibtex "engr446milestone1"
    - pdflatex "engr446milestone1".tex
  artifacts:
    paths:
      - "/builds/studentdavidli/ENGRCoopReportTemplate/Auxillary-Reports/project-background-I/*.pdf"

engineering-analysis-II:
  stage: auxReports
  script:
    - cd /builds/studentdavidli/ENGRCoopReportTemplate/Auxillary-Reports/engineering-analysis-II
    - pdflatex "engr446milestone2".tex 
    - bibtex "engr446milestone2"
    - pdflatex "engr446milestone2".tex
  artifacts:
    paths:
      - "/builds/studentdavidli/ENGRCoopReportTemplate/Auxillary-Reports/engineering-analysis-II/*.pdf"
      
pages:
  stage: publish
  script:
    - mv /builds/studentdavidli/ENGRCoopReportTemplate/Auxillary-Reports/engineering-analysis-II/ public/
    - mv /builds/studentdavidli/ENGRCoopReportTemplate/Auxillary-Reports/project-background-I/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only: 
    - master